name: Publish lib to npm

on:
  push:
    branches: ["main"]
    paths:
      - "lib/**"

  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint:lib

      - name: Typecheck
        run: pnpm run tsc:lib

      - name: Test
        run: pnpm run test

      - name: Create release PR or publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run build:lib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
